### ISSUE TITLE
information/caveats to include in text/faqs/etc

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/infinitylists#21]
it's currently NSW only
records from 1923 onwards only
collections and iNat only (so no bionet or similar)

any others?

**Comment by fontikar** [comment]
coordinateuncertainty <1000m or NA

**Comment by tmesaglio** [comment]
building on Fonti's comment, this will exclude any species in iNat with generalised/obscured locations (uncertainty = 28,000-31,000)

**Comment by tmesaglio** [comment]
download only = species level observations

**Comment by tmesaglio** [comment]
we take no responsibility for misIDs of records

**Comment by tmesaglio** [comment]
done
