### ISSUE TITLE
generalization via Fonti's work with galah

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/infinitylists#22]
I was thinking that this function could take a state and a taxon.   

e.g. 

```
create_map_app("Lepidoptera", "VIC")
```

would make a local app for Victorian Butterflies.  

```
create_map_app("fungi", "WA")
```

Would make a local app for WA mushrooms?

What do you think?  Too ambitious?

**Comment by tmesaglio** [comment]
I love the idea

**Comment by fontikar** [comment]
LOVE LOVE LOVE

**Comment by fontikar** [comment]
This is like traits.build but map-app.build

**Comment by wcornwell** [comment]
Tassie butterflies too hard. Starting with NSW butterflies.

**Comment by tmesaglio** [comment]
when picking a non-plant taxon, is our code pulling in sound-based records as well as photo-based ones? Lots of bird, cicada, frog calls on iNat that have gone into ALA

**Comment by wcornwell** [comment]
going to an all Australia approach leads to a 94MB parquet file and it slows down the app a bit.  But it does work: 
<img width="761" alt="Screenshot 2023-08-25 at 1 42 02 pm" src="https://github.com/traitecoevo/infinitylists/assets/5534161/5e8a03d4-c997-4b1b-bd2a-f2fb77019ced">
