### ISSUE TITLE
chose the older point in the target area, relative to the more recent one in the buffer

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/infinitylists#25]
something about the sorting isn't working as designed

**Comment by wcornwell** [comment]
@tmesaglio can you check this?

**Comment by tmesaglio** [comment]
This is working for the table, but seemingly not for the map! 
Load in Acacia, Grants Head place, 1 km buffer

In the table, two species only are listed as in buffer --> baueri and brownii

Yet look at the map, and there are three points in the buffer zone --> baueri, brownii **and** longifolia

I just checked the iNat records, and the buffer longifolia is from 2022, the target longifolia are from 2019-2020

so the map is still erroneously showing the most recent record in the buffer

**Comment by tmesaglio** [comment]
![image](https://github.com/traitecoevo/infinitylists/assets/48739968/9777d690-6f40-41da-839a-d64addc2a1bb)

**Comment by tmesaglio** [comment]
and indeed it's actually doing that for melanoxylon too, the point was hiding behind another one

**Comment by tmesaglio** [comment]
the flow on effect also of this is that all of the following columns erroneously correspond to that most recent buffer record instead of the most recent target one:
most recent obs
lat 
long
voucher location
observed by

**Comment by tmesaglio** [comment]
so in essence from what I can tell, the problem still exists in all places except for the 'in target area' column, that's the only place the problem is fixed

**Comment by wcornwell** [comment]
ok.  this is all about proper table sorting, but something about the shiny version of this is confusing me.

**Comment by wcornwell** [comment]
<img width="1008" alt="Screenshot 2023-08-28 at 2 39 45 pm" src="https://github.com/traitecoevo/infinitylists/assets/5534161/488121cb-abb7-4d0e-af5a-f96746d3de5d">

**Comment by tmesaglio** [comment]
another weird bug with this. Acacia suaveolens appears in both the target and buffer
![image](https://github.com/traitecoevo/infinitylists/assets/48739968/17ed355a-71ad-49cc-881f-c093c96af654)

**Comment by tmesaglio** [comment]
is there a way to purely restrict the buffer entities to species not in target? That would be ideal to me, so even if species A has been only collected in target, but there's a photograph in the buffer, I don't care about that photo record because it's still species A

**Comment by wcornwell** [comment]
Might need @fontikar help with the dplyr on this one.

**Comment by wcornwell** [comment]
might have got it, try again

**Comment by tmesaglio** [comment]
seems fixed
