### ISSUE TITLE
use current location from phone/computer option

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/infinitylists#28]

**Comment by fontikar** [comment]
This would be cool!

**Comment by wcornwell** [comment]
```If you're developing a web application with R (using Shiny, for example) and want more accurate location data, you'd typically request location access in the browser using JavaScript, then pass that data to your R backend.```

**Comment by wcornwell** [comment]
https://github.com/AugustT/shiny_geolocation

**Comment by wcornwell** [comment]
https://www.r-bloggers.com/2017/03/4-tricks-for-working-with-r-leaflet-and-shiny/

**Comment by fontikar** [comment]
> https://github.com/AugustT/shiny_geolocation
> 
> (i'm a bit scared of trying this tbh)

I tried this using their simple example and it failed. Not worth it!

**Comment by tmesaglio** [comment]
big time bugs, with different behaviour on desktop vs phone

When I use my desktop:

I select current location, and it works fine (albeit really poor accuracy, more than 1.5 km wrong). When I then swap to the choose lat/longmodality, however, and click go with the default coordinates entered, it 'mimics' my current location.

If I manually change the coordinates, it works and goes to the correct location. BUT, if after doing this I then swap back to current location, now the current location does not work and instead it mimics the choose lat/long coordinates. Once you have gone in this direction, it is impossible to get current location to work without refreshing the page

On mobile:

Current location does not work at all. When you first open the app, the current location modality already mimics the default choose lat/long coordinates. Changing those coordinates in choose lat/long works, and then when you swap back to current location, it will update and mimic the new spot.

So on mobile, the mimicry is one way, on desktop it's kind of two way

**Comment by fontikar** [comment]
Thanks for sharing what crazy mimicry indeed. Having a look now!

**Comment by fontikar** [comment]
My thinking is current location is coming in as `latitude` and `longitude` as inputids

```
   function onSuccess (position) {
      setTimeout(function () {
          var coords = position.coords;
          console.log(coords.latitude + ", " + coords.longitude, "," + coords.accuracy);
          Shiny.onInputChange("geolocation", true);
          Shiny.onInputChange("latitude", coords.latitude);
          Shiny.onInputChange("longitude", coords.longitude);
          Shiny.onInputChange("accuracy", coords.accuracy);
      }, 1100)
  }
  });
  ```
  
  and so is choose your own lat/long. 
  
  ```
   conditionalPanel(
          condition = "input.inputType == 'choose'",
          numericInput(
            "latitude",
            "Latitude",
            value = -33.8688,
            min = -90,
            max = 90,
            step = 0.00001),
          numericInput(
            "longitude",
            "Longitude",
            value = 148.2093,
            min = -180,
            max = 180,
            step = 0.00001
```
  And choose your lat/long is likely overwriting what is determined by JS.  
  
I can give each method - different input ids and bring them together in the server later.

**Comment by fontikar** [comment]
So where in the server are lat and long used and what mechanism can bring 4 different input ids together...

**Comment by fontikar** [comment]
lat and long ids are used in 

```
   circle_polygon <- eventReactive(input$executeButton, {
      lat <- tryCatch(
        as.numeric(input$latitude),
        error = function(e)
          NA
      )
      long <-
        tryCatch(
          as.numeric(input$longitude),
          error = function(e)
            NA
        )
      radius_m <-
        tryCatch(
          as.numeric(input$radiusChoice),
          error = function(e)
            NA
        )
```

**Comment by fontikar** [comment]
Peter on iPhone: 
![IMG_3385](https://github.com/traitecoevo/infinitylists/assets/12161802/5df918fb-5116-40e2-939c-ffc8763bec4d)
Speed test: 
![IMG_3386](https://github.com/traitecoevo/infinitylists/assets/12161802/e53bae0c-328c-409a-a909-88d81354886e)

**Comment by fontikar** [comment]
Closing this! Yay
