### ISSUE TITLE
pick color scheme for polygon and buffer

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/infinitylists#30]

**Comment by tmesaglio** [comment]
possibly red for target, purple for buffer? Can we try that

**Comment by tmesaglio** [comment]
or orange for buffer

**Comment by wcornwell** [comment]
https://r-graph-gallery.com/42-colors-names.html

**Comment by wcornwell** [comment]
<img width="869" alt="Screenshot 2023-08-28 at 3 02 48 pm" src="https://github.com/traitecoevo/infinitylists/assets/5534161/07d11d4c-6946-4603-9e62-da35eb5beb9c">
Red/purple

**Comment by wcornwell** [comment]
<img width="869" alt="Screenshot 2023-08-28 at 3 02 48 pm" src="https://github.com/traitecoevo/infinitylists/assets/5534161/66001a62-6440-4305-8ffd-3c8bcbdedb4e">
red/purple

**Comment by tmesaglio** [comment]
current red + orange is good
