### ISSUE TITLE
UI Organization

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/infinitylists#34]
-   Group related UI elements within wellPanel or box for better visual organization.
-   Use sidebarLayout with sidebarPanel and mainPanel ?

**Comment by fontikar** [comment]
Heres an app that uses the white space we are neglecting so far. Thoughts? https://chatlize.ai/

**Comment by wcornwell** [comment]
<img width="874" alt="Screenshot 2023-09-06 at 2 53 42 pm" src="https://github.com/traitecoevo/infinitylists/assets/5534161/292befbd-d39e-4583-a2d8-6b1c5b6a97d9">

**Comment by wcornwell** [comment]
putting the map and table on different tabs makes it a little less weird that filtering the table doesn't affect the map and clicking on the map doesn't affect the table.

**Comment by tmesaglio** [comment]
yeah I don't mind that. But which tab should go first: the table or the map?

**Comment by wcornwell** [comment]
map first looks a little more visually friendly for new users

**Comment by wcornwell** [comment]
I think we're good, ready for user feedback
