### ISSUE TITLE
linking to ALA obs url for collections

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/infinitylists#37]
shouldn't be too hard.

**Comment by fontikar** [comment]
I think we need `taxonConceptID` using galah_select during download

**Comment by fontikar** [comment]
I thought this was sorted in TaxonConceptID but doesn't seem to be the case

**Comment by fontikar** [comment]
https://biocache.ala.org.au/occurrences/86488ecf-b65a-4c02-bdc6-8280bc14277e

Looks like we can grab recordID and paste into URL

**Comment by wcornwell** [comment]
yup, i have it working locally, but still dealing with the file size issue

**Comment by wcornwell** [comment]
done
