### ISSUE TITLE
sound-based records erroneously getting annotated as 'Photograph' in the voucher type column

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/infinitylists#38]
iNat records with only sound recordings (eg https://www.inaturalist.org/observations/175522145) that are in the ALA (https://biocache.ala.org.au/occurrences/86488ecf-b65a-4c02-bdc6-8280bc14277e) are getting pulled in by the app. This is good and working as expected. However, they are getting annotated as 'Photograph' in our voucher type column, which is not desirable given it's misleading.

How can we annotate these records correctly in the voucher type column? The 'record type' field in the ALA does not differentiate between photos and sounds (they all get called 'human observation')

**Comment by fontikar** [comment]
cc_occurrences <- 
  galah_call() |>                               
  galah_identify("Cicadoidea") |>   
  galah_filter(year == 2022) |> 
  galah_select(group = c("basic"), sounds,imageID, basisOfRecord) |> 
  atlas_occurrences() 

Better case_when using sounds, imageID and basisOfRecord when creating Voucher type

**Comment by wcornwell** [comment]
this is done on the alalink branch, but not ready to merge yet

**Comment by wcornwell** [comment]
done
