### ISSUE TITLE
include links in the FAQs

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/infinitylists#42]
some things could use live links (e.g. linking to ALA)

**Comment by tmesaglio** [comment]
for sure, I was going to do that; will they automatically hyperlink?

**Comment by fontikar** [comment]
Not a fun task but possible: https://community.rstudio.com/t/hyperlink-portion-of-text-in-shiny-server-text-block/67328/2

**Comment by tmesaglio** [comment]
I added links, but left them un-hyperlinked
