### ISSUE TITLE
Are we resurrecting the native/non-native column?

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/infinitylists#43]
or is this too tricky with the non-plant taxa?

**Comment by wcornwell** [comment]
it's a bit messy problem. but should ask the BGoS people if it's an important feature

**Comment by fontikar** [comment]
OTherwise we can try use this: https://griis.org/ ? I used it for ALA/Inverts Aus, its not a perfect solution but its better than nothing?

**Comment by tmesaglio** [comment]
For every single non-plant species, there are only two cases where a non-native status has to be manually applied, every other thing is native: these two are Danaus plexippus and Pieris rapae (both butterflies)

**Comment by wcornwell** [comment]
<img width="1131" alt="Screenshot 2023-09-12 at 3 54 55 pm" src="https://github.com/traitecoevo/infinitylists/assets/5534161/1c9abb06-91f0-4ad7-bc81-c929feb1b284">

**Comment by wcornwell** [comment]
I'm not sure where it should go in the table...any opinions about the ordering of the columns?

**Comment by tmesaglio** [comment]
second column I reckon, directly after species

also, I think we can rename the voucher location column just to 'voucher', that will remove some white space

**Comment by wcornwell** [comment]
what about "Repository" for what is now "Voucher Location"?

**Comment by tmesaglio** [comment]
yeah that sounds good
