### ISSUE TITLE
Issues with CSV download

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/infinitylists#44]
1. Some weird behaviour with the common name column in the export, eg Gleichenia dicarpa has the common name 'Waewae KÅtuku', and Pittosporum undulatum is Snowdrop Tree (lord Howe)
2. The voucher location column doesnt get populated by the voucher link for collections, only the herbarium abbreviation (whereas iNat records get the link to the observation)

**Comment by wcornwell** [comment]
I made some changes after downloading the plant data (which takes a few hours).  

Maybe check for butterflies?  

Also someone requested that the download be *all* records not just the most recent, so I *think* that's what it's doing now.  Maybe we should note that in the FAQs:

"I'd like to see all collections not just the most recent for each species.  How do I do that?"

**Comment by tmesaglio** [comment]
> Maybe check for butterflies?
No hyperlinks for vouchered butterfly records either

> Also someone requested that the download be all records not just the most recent, so I think that's what it's doing now
It's definitely doing that right now

**Comment by tmesaglio** [comment]
> Maybe we should note that in the FAQs:

Already done -->
"This will download a CSV file containing all records within the target area (and buffer, if selected), not just the most recent records that are presented in the table."

**Comment by wcornwell** [comment]
I think I took common name out of later downloads as it looked too messy, so that should go away on the next iteration

**Comment by tmesaglio** [comment]
that's fine by me

**Comment by wcornwell** [comment]
html links now that work, but excel doesn't like them :( <img width="566" alt="Screenshot 2023-09-06 at 6 08 55 pm" src="https://github.com/traitecoevo/infinitylists/assets/5534161/499f354c-390b-418b-99c2-ae31065c7835">

**Comment by wcornwell** [comment]
probably better with just the url and not the ugly html: 
<img width="469" alt="Screenshot 2023-09-06 at 6 18 35 pm" src="https://github.com/traitecoevo/infinitylists/assets/5534161/ba9268dd-f46e-4a14-9273-a5a3f818d9af">

**Comment by wcornwell** [comment]
should be fixed i think
