### ISSUE TITLE
Error with map and table for butterflies under specific conditions

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/infinitylists#48]
1. Open Opera and go to https://posit-connect-unsw.intersect.org.au/infinitylists/
2. Select Choose a lat/long in Australia, and enter these coordinates: -34.068875, 151.036703
3. Select butterflies parquet
4. Select radius of either 10km or 50km and click go
5. The search executes, but the map and table do not appear, and this error message is presented twice: 
"Error: An error has occurred. Check your logs or contact the app author for clarification."

When running the app locally in R, exact same problem occurs, but the error message is different: 
"Error: object 'Record Id' not found"

Using any other radius value for butterflies does not generate the issue

As a test (in Opera), I then changed the coordinates for butterflies + 10km radius slightly to -33.068875, 150.036703, and got a different error!
A popup dialogue box appears:
![image](https://github.com/traitecoevo/infinitylists/assets/48739968/83ab52c0-5a4e-4b38-8a50-90a9c585b06b)

When I click ok on that box, the map generates fine, but the table is missing (although the column headings are all there) 

Same thing occurs for butterflies + 50km for the new coordinates, but in the dialogue window, it says DataTables_Table_3 instead of Table_2

**Comment by tmesaglio** [comment]
and in fact after this last step, I seem to have broken the app for all taxa and all radius values, the dialogue window keeps popping up and the table is permanently broken

**Comment by tmesaglio** [comment]
Further notes: butterflies seem to be broken at 10km and 50km for any coordinates at all

**Comment by tmesaglio** [comment]
Extra notes....: 
Marsupials also broken at 10 and 50
Odonata broken only at 50
Cicadas ok at all values
Plants ok at all values

**Comment by wcornwell** [comment]
i got it.  i deleted one too many columns downloading latest version today

**Comment by wcornwell** [comment]
possibly fixed?

**Comment by tmesaglio** [comment]
fixed for me
