### ISSUE TITLE
Improve performance of taxa_genus

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/infinitylists#51]
Got this cool and seemingly helpful warning so we can improve on performance
```Warning: The select input "taxa_genus" contains a large number of options; consider using server-side selectize for massively improved performance. See the Details section of the ?selectizeInput help topic.```

**Comment by wcornwell** [comment]
i also thought it was very helpfully phrased warning, but then i tried it and it was worse :(

**Comment by fontikar** [comment]
Interesting...me neither! lets close this!
