### ISSUE TITLE
File name of downloaded CSV no longer contains buffer information

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/infinitylists#53]
When you download a CSV, you get a file name like this for any standard search: 
"North Head - Sydney Harbour Federation Trust-Australia-Plantae-2023-09-05"

Before we added the Plantae-all file today, downloading a CSV after applying a buffer would generate a file name like this:
"North Head - Sydney Harbour Federation Trust-Australia-Plantae-2023-09-05 with 2km buffer"

I really like this naming behaviour. As of today, however, downloading a CSV with buffer generates the exact same file name as downloading a CSV without a buffer. 

Would love to revert this if possible

**Comment by wcornwell** [comment]
i think this is fixed, can you check @tmesaglio ?

**Comment by tmesaglio** [comment]
works well
