### ISSUE TITLE
windows testing--github install not currently working on windows machines

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/infinitylists#66]

**Comment by wcornwell** [comment]
> open_dataset("C:/Users/Will/AppData/Local/R/win-library/4.3/infinitylists/data/Australia-Plantae-2023-09-14.parquet")
Error in `open_dataset()`:
! IOError: Error creating dataset. Could not read schema from 'C:/Users/Will/AppData/Local/R/win-library/4.3/infinitylists/data/Australia-Plantae-2023-09-14.parquet'. Is this a 'parquet' file?: Could not open Parquet input source 'C:/Users/Will/AppData/Local/R/win-library/4.3/infinitylists/data/Australia-Plantae-2023-09-14.parquet': Couldn't deserialize thrift: TProtocolException: Invalid data
Run `rlang::last_trace()` to see where the error occurred.

**Comment by wcornwell** [comment]
possibly fixed here: https://github.com/traitecoevo/infinitylists/commit/1af26683d9feef93e16ad941101f61d136403a2d @tmesaglio can check

**Comment by tmesaglio** [comment]
I can run it on windows
